// <auto-generated />
using GreenShop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenShop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220921031715_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GreenShop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "William McDonough and Michael Braungart imagine how human society might, at last, begin to rewrite its role in the history of the natural world. In The Upcycle, the best-selling authors offer numerous fascinating scenarios in which humans transcend the role of mere stewards of the planet. Instead, they suggest, why not become co-creators of the simplest invention ever: abundance?",
                            ImageUrl = "https://kbimages1-a.akamaihd.net/d7bb4cc8-ee43-4156-9782-e271d2f79e1d/353/569/90/False/the-upcycle.jpg",
                            Price = 10m,
                            Title = "The Upcycle: Beyond Sustainability—Designing for Abundance"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Written by award-winning Canadian architect, Teresa Coady, this book is both a call to action and a plan. It starts by tracing how we ended up with our unsustainable concrete jungles, and then it lays out principles and techniques for how to build a better future.\n\nIts highly readable prose is for anyone who wants be part of, or simply imagine, a more natural and sustainably built environment.",
                            ImageUrl = "https://zerowastememoirs.com/wp-content/uploads/2020/10/Screenshot-2020-10-24-at-16.35.34.png.webp",
                            Price = 10m,
                            Title = "Rebuilding Earth: Designing Ecoconscious Habitats for Humans"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Written by William McDonough and Michael Braungart. Did you know that up to 90% of the materials used in traditional manufacturing models ends up as waste? This book challenges the way the traditional “cradle to grave” cycle works and envisions a world where we don’t have to harm the natural environment in order to create new products.",
                            ImageUrl = "https://zerowastememoirs.com/wp-content/uploads/2020/10/Screenshot-2020-10-24-at-16.25.09.png.webp",
                            Price = 10m,
                            Title = "Cradle to Cradle: Remaking the Way We Make Things"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
